package ca.sait.backup.model.entity;

public enum UserNotificationEnum {
    SUPPORT_TICKET_STATUS_UPDATE, SUPPORT_TICKET_MESSAGE,
    PROJECT_INVITATION, PROJECT_ASSET_REQUEST, PROJECT_ASSET_APPROVED, PROJECT_ASSET_DENIED,
    SYSTEM_UPDATE, SYSTEM_DOWNTIME
}
